# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-24 12:34
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=250)),
                ('dcontact', models.CharField(max_length=250)),
                ('daddress', models.TextField()),
                ('dlicense', models.CharField(max_length=250)),
                ('daadhar', models.DecimalField(decimal_places=0, max_digits=12)),
                ('dphoto', models.ImageField(upload_to=accounts.models.upload_photo)),
                ('dscan', models.FileField(upload_to=accounts.models.upload_file)),
            ],
        ),
    ]
