# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-24 16:29
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170624_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_user),
        ),
    ]
