# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170624_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='id',
        ),
        migrations.AlterField(
            model_name='drivers',
            name='dlicense',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
