# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
