# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='dphoto',
            field=models.TextField(blank=True),
        ),
    ]
