# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-24 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('gps_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=250)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Drivers')),
            ],
        ),
    ]
